name: SetRankPB
version: 1.3.0
softdepend: [Spout]
main: com.baummann.setrankpb.SetRankPB
commands:
   setrank:
      description: Changes someone's rank.
      usage: /<command> [Player] [Rank]
      aliases: [rank]
   promotion:
      description: Promotion with payment.
      usage: /<command> [option]
      aliases: [promo]
permissions:
   setrankpb.rank.<rank>:
      description: Ability to rank to a specific rank.
      default: op
   setrankpb.rankall:
      description: Permission to rank to every rank.
      default: op
   setrankpb.iconomy.price:
      description: Ability to view a price of a rank.
      default: op
   setrankpb.iconomy.buy.<rank>:
      description: Ability to buy a specific rank.
      default: op
   setrankpb.iconomy.buy.*:
      description: Ability to buy all ranks.
      default: op
   setrankpb.iconomy.pricelist:
      description: Permission to view the price list.
      default: op
      